/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionTabs: typeof import('./src/components/AccordionTabs.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BulletList: typeof import('./src/components/BulletList.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    IconCurvyArrow: typeof import('./src/components/icons/IconCurvyArrow.vue')['default']
    IconPacman: typeof import('./src/components/icons/IconPacman.vue')['default']
    IconPacmanGhost: typeof import('./src/components/icons/IconPacmanGhost.vue')['default']
    IntroSection: typeof import('./src/components/IntroSection.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    LeftColumn: typeof import('./src/components/LeftColumn.vue')['default']
    Options: typeof import('./src/components/Options.vue')['default']
    RightColumn: typeof import('./src/components/RightColumn.vue')['default']
    Role: typeof import('./src/components/Role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TitleDescList: typeof import('./src/components/TitleDescList.vue')['default']
    TriviaGame: typeof import('./src/components/TriviaGame.vue')['default']
    WhatNow: typeof import('./src/components/WhatNow.vue')['default']
    WhatNowLink: typeof import('./src/components/WhatNowLink.vue')['default']
  }
}
